export const CHANGE_RADIO_CATEGORY = "CHANGE_RADIO_CATEGORY";
export const CHANGE_CURRENT_ID = "CHANGE_CURRENT_ID";
export const CHANGE_RADIO_RECOMMEND = "CHANGE_RADIO_RECOMMEND";
export const CHANGE_HOT_RADIO = "CHANGE_HOT_RADIO";
export const CURRENT_PAGE = "CURRENT_PAGE";