export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_CURRENT_CATEGORY = "CHANGE_CURRENT_CATEGORY";
export const CHANGE_CATEGORY_SONG = "CHANGE_CATEGORY_SONG";
export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
export const CHANGE_SHOW_CATEGORY = "CHANGE_SHOW_CATEGORY";