export const CHANGE_TOP_LIST = "CHANGE_TOP_LIST";
export const CHANGE_CURRENT_INDEX = "CHANGE_CURRENT_INDEX";
export const CHANGE_PLAT_LIST = "CHANGE_PLAT_LIST";
export const CHANGE_RANKING_COMMENT = "CHANGE_RANKING_COMMENT";
export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";